bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import mark_messages_as_read


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('',include("store.urls")),
    path('dashboard/',include("dashboard.urls")),
    path('mark_messages_as_read/', mark_messages_as_read, name='mark_messages_as_read'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bookid>', views.cart_add, name='cart_add'),
	path('remove/<int:bookid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bookid>/<int:quantity>', views.cart_update, name='cart_update'),
]

dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'dashboard'  

urlpatterns = [
    path('', views.index, name="dashboard"),
    path('orders', views.orders, name="orders"),

    path('login', views.admin_login, name="admin_login"),
	path('logout', views.admin_logout, name="admin_logout"),

    path('order/<int:order_id>/', views.order_details, name='order_details'),
    path('add_book/', views.add_book_view, name='add_book'),
    path('books_list/', views.books_list, name='books_list'),
    path('edit_book/<int:book_id>/', views.edit_book, name='edit_book'),
    path('change_payment_status/<int:order_id>/', views.change_payment_status, name='change_payment_status'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    path('mark_messages_as_read/', views.mark_messages_as_read, name='mark_messages_as_read'),
    path('all_messages/', views.all_messages, name='all_messages'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('all_categories/', views.categoriesView, name='all_categories'),
    
    path('add_writer/', views.add_writer, name='add_writer'),
    path('writers/', views.writers, name='writers'),
    path('delete_writer/<int:writer_id>/', views.delete_writer, name='delete_writer'),





]

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
	path('', views.order_list, name="order_list"),
	path('<int:id>', views.order_details, name="order_details"), 
	path('shipping/', views.order_create, name="order_create"),
	path('pdf/<int:id>',views.pdf.as_view(), name="pdf"),
    
   
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
	path('', views.index, name = "index"),
	path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),
	path('book/<int:id>', views.get_book, name="book"),
	path('books', views.get_books, name="books"),
	path('category/<int:id>', views.get_book_category, name="category"),
	path('writer/<int:id>', views.get_writer, name = "writer"),

	path('send_message/', views.send_message, name='send_message'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
# dashboard/forms.py
from django import forms
from store.models import Book, Category, Writer

from django.core.exceptions import ValidationError


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'  # Include all fields from the Book model except 'created' and 'updated'

    # Define ModelChoiceFields for Category and Writer
    writer = forms.ModelChoiceField(
        queryset=Writer.objects.all(),
        empty_label="Select a writer",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label="Select a category",
        widget=forms.Select(attrs={'class': 'form-control'})
    )



class WriterForm(forms.ModelForm):
    class Meta:
        model = Writer
        fields = ['name', 'slug', 'bio', 'pic']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'slug', 'icon']

    name = forms.CharField(
        label='Category Name',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Category Name...'})
    )
    slug = forms.SlugField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Slug'
    )
    icon = forms.ImageField(
        widget=forms.FileInput(attrs={'class': 'custom-file-input'}),
        label='Icon'
    )

dashboard/views.py

from django.shortcuts import render, redirect, get_object_or_404
from order.models import Order, OrderItem
from store.models import  Writer, Category, Book, Message
from django.db.models import Q
from django.contrib.auth.models import User
from django.db import transaction
from django.core.exceptions import ValidationError
from dashboard.forms import BookForm
from django.http import JsonResponse
from django.db.models import Sum
from django.contrib import messages
from .forms import WriterForm
from django.core.mail import send_mail
from django.template.loader import render_to_string

from django.urls import path
from . import views

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect


def admin_required(view_func):
    def wrapped(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            return view_func(request, *args, **kwargs)
        else:
            return redirect('store:index')  # Redirect non-admin users to the store app's index
    return wrapped



# Apply the admin_required decorator to restrict access to admin users
@admin_required
def index(request):
    users_count = User.objects.count()
    total_books = Book.objects.count()
    total_categories = Category.objects.count()
    total_writers = Writer.objects.count()
    total_orders = Order.objects.count()
    # Calculate total earnings from paid orders
    total_earnings = Order.objects.filter(paid=True).aggregate(total_earnings=Sum('payable'))['total_earnings'] or 0
    # Calculate the count of unpaid orders
    total_unpaid_orders = Order.objects.filter(paid=False).count()

    unread_messages = Message.objects.filter(read=False).count()
    # Fetch the last 4 messages
    last_4_messages = Message.objects.filter(read=False)[:4]
    # last 4 orders display 
    last_4_orders = Order.objects.all().order_by('-created')[:5]

    paid_orders = Order.objects.filter(paid=True)


  

    # Mark the fetched messages as read
    # for message in last_4_messages:
    #     message.read = True
    #     message.save()

    context = {
    'users_count': users_count,
    'total_books': total_books,
    'total_categories': total_categories,
    'total_writers': total_writers,
    'total_orders': total_orders,
    'total_earnings': total_earnings,
    'total_unpaid_orders': total_unpaid_orders,
    'unread_messages': unread_messages,
    'last_4_messages': last_4_messages,
    'last_4_orders': last_4_orders,
    'paid_orders': paid_orders,

    }

    return render(request, 'index.html', context )

 
def admin_login(request):
    if request.user.is_authenticated:
        return redirect('dashboard:dashboard')  # Redirect admin users to the dashboard
    else:
        if request.method == "POST":
            user = request.POST.get('user')
            password = request.POST.get('pass')
            auth = authenticate(request, username=user, password=password)
            if auth is not None:
                login(request, auth)
                if request.user.is_staff:  # Check if the logged-in user is an admin
                    return redirect('dashboard:dashboard')  # Redirect admin users to the dashboard
                else:
                    return redirect('store:index')  # Redirect non-admin users to the store app's index
            else:
                messages.error(request, 'Username and password do not match')

    return render(request, "login.html")


def admin_logout(request):
    logout(request)
    return redirect('store:index')	


@admin_required
def all_messages(request):
    messages = Message.objects.all()
    return render(request, 'messages.html', {'messages': messages})


@admin_required
def mark_messages_as_read(request):
    if request.method == 'POST':
        # Get the message IDs from the request data
        message_ids = request.POST.getlist('message_ids')

        # Update the messages as read
        Message.objects.filter(id__in=message_ids).update(read=True)

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})


@admin_required
def orders(request):
    query = request.GET.get("query")
    orders = Order.objects.all()
    order_items = {}
    for order in orders:
        order_items[order.id] = OrderItem.objects.filter(order=order)
    
    orders = Order.objects.all() 

    # If a query is provided, filter orders by name
    if query:
        orders = orders.filter(Q(name__icontains=query))

    context = {
        'orders': orders,
        'order_items': order_items,
         'query': query, 
    }
    
    return render(request, 'orders.html', context)


@admin_required
def order_details(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order_items = OrderItem.objects.filter(order=order)

    # Determine payment status
    payment_status = "Paid" if order.paid else "Unpaid"

    context = {
        'order': order,
        'order_items': order_items,
        'payment_status': payment_status,  
    }

    return render(request, 'order_details.html', context)


# category adding
from .forms import CategoryForm

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dashboard:all_categories')  # Redirect to the dashboard or your preferred URL

    else:
        form = CategoryForm()

    return render(request, 'add_category.html', {'form': form})


# categories List
def categoriesView(request):
    categories = Category.objects.all()
    return render(request, 'all_categories.html', {'categories': categories})

# delete a category
def delete_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    category.delete()
    return redirect('dashboard:all_categories')


def add_writer(request):
    if request.method == 'POST':
        form = WriterForm(request.POST, request.FILES)  # Pass both POST data and files for file fields
        if form.is_valid():
            form.save()  # Save the form data to the database
            return redirect('dashboard:writers')  # Redirect to the list of writers or another appropriate URL
    else:
        form = WriterForm()  # Create a new, empty form instance

    context = {'form': form}
    return render(request, 'add_writers.html', context)

# display writers
def writers(request):
    writers = Writer.objects.all()
    return render(request, 'all_writers.html', {'writers': writers})


# delete writers

def delete_writer(request, writer_id):
    writer = get_object_or_404(Writer, id=writer_id)

    if request.method == 'POST':
        # If a POST request is made (usually from a form submission), delete the writer
        writer.delete()
        return redirect('dashboard:writers')  # Redirect to the writer list page or another appropriate URL after deletion

    # If a GET request is made, display a confirmation page before deletion
    context = {'writer': writer}
    return render(request, 'dashboard/delete_writer.html', context)


@admin_required
def change_payment_status(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        payment_status = request.POST.get('payment_status')
        if payment_status == 'paid' and not order.paid:
            order.paid = True
            order.save()

            # Send email to customer
            subject = 'Payment Confirmation'
            message = f'Thank you for your order. Your payment for Order #{order.id} has been confirmed.'
            from_email = 'muhsinbookstore1.com'  # Your email address
            recipient_list = [order.email]

            email_context = {
                'order': order,
                # Add more context data as needed
            }
            html_message = render_to_string('payment_confirmation_email.html', email_context)

            send_mail(subject, message, from_email, recipient_list, html_message=html_message)

    return redirect('dashboard:orders')




@admin_required
def add_book_view(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dashboard:books_list')
    else:
        form = BookForm()

    writers = Writer.objects.all()
    categories = Category.objects.all()

    return render(request, 'add_book.html', {'form': form, 'writers': writers, 'categories': categories})



# this lists the books
@admin_required
def books_list(request):
    books = Book.objects.all()

    query = request.GET.get('query')
    books = Book.objects.all()

    if query:
        books = books.filter(
            Q(name__icontains=query) | Q(writer__name__icontains=query)  | Q(category__name__icontains=query)
        )

    context = {
        'books': books,
    }
    return render(request, 'books_list.html', context)


# deletes the books
@admin_required
def delete_book(request, book_id):
    book = Book.objects.get(pk=book_id)
    book.delete()
    return redirect('dashboard:books_list')

@admin_required
def edit_book(request, book_id):
    # Retrieve the book instance from the database
    book = get_object_or_404(Book, id=book_id)

    if request.method == 'POST':
        # If it's a POST request, process the form data
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            # Check if writer and category fields are present in the form data

order/views.py
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import View
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from cart.cart import Cart
from .models import Order, OrderItem
from .forms import OrderCreateForm
from .pdfcreator import renderPdf
from requests.auth import HTTPBasicAuth

from django.contrib import messages



def order_create(request):
	cart = Cart(request)
	if request.user.is_authenticated:
		customer = get_object_or_404(User, id=request.user.id)
		form = OrderCreateForm(request.POST or None, initial={"name": customer.first_name, "email": customer.email})
		if request.method == 'POST':
			if form.is_valid():
				order = form.save(commit=False)
				order.customer = User.objects.get(id=request.user.id)
				order.payable = cart.get_total_price()
				order.totalbook = len(cart) # len(cart.cart) // number of individual book
				order.save()

				for item in cart:
					OrderItem.objects.create(
						order=order, 
						book=item['book'], 
						price=item['price'], 
						quantity=item['quantity']
						)
				cart.clear()
				return render(request, 'order/successfull.html', {'order': order})

			else:
				messages.error(request, "Fill out your information correctly.")

		if len(cart) > 0:
			return render(request, 'order/order.html', {"form": form})
		else:
			return redirect('store:books')
	else:
		return redirect('store:signin')
			
def order_list(request):
	my_order = Order.objects.filter(customer_id = request.user.id).order_by('-created')
	paginator = Paginator(my_order, 5)
	page = request.GET.get('page')
	myorder = paginator.get_page(page)

	return render(request, 'order/list.html', {"myorder": myorder})

def order_details(request, id):
	order_summary = get_object_or_404(Order, id=id)

	if order_summary.customer_id != request.user.id:
		return redirect('store:index')

	orderedItem = OrderItem.objects.filter(order_id=id)
	context = {
		"o_summary": order_summary,
		"o_item": orderedItem
	}
	return render(request, 'order/details.html', context)


from decimal import Decimal

class pdf(View):
    def get(self, request, id):
        try:
            query = get_object_or_404(Order, id=id)
        except:
            raise Http404('Content not found')

        total_amount = 0
        for item in query.orderitem_set.all():
            total_amount += item.price * item.quantity

        context = {
            "order": query,
            "total_amount": total_amount,
        }
        article_pdf = renderPdf('order/pdf.html', context)
        return HttpResponse(article_pdf, content_type='application/pdf')

dashboard/templates/add_category.html
{% extends "base.html" %}
{% block title %}Add Books{% endblock %}
{% block page_heading %}Add Books{% endblock %}



{% block content %}

    <div class="row">
        <div class="col-lg-6">
            <div class="p-5">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                
                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}">Category Name:</label>
                        {{ form.name }}
                    </div>
                
                    <div class="form-group">
                        <label for="{{ form.slug.id_for_label }}">Slug:</label>
                        {{ form.slug }}
                    </div>
                
                    <div class="form-group">
                        <label for="{{ form.icon.id_for_label }}">Icon:</label>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="{{ form.icon.id_for_label }}" name="icon">
                            <label class="custom-file-label" for="{{ form.icon.id_for_label }}">Choose file</label>
                        </div>
                        {% if form.icon.errors %}
                            <div class="text-danger">
                                {{ form.icon.errors }}
                            </div>
                        {% endif %}
                    </div>
                    
                
                    <button type="submit" class="btn btn-primary btn-user btn-block mb-1">
                        Add Category
                    </button>
                </form>
                
            </div>
        </div>

      
    </div>


  
{% endblock %}
{% block generate_report_button %}{% endblock %}




dashboard/templates/all_categories.html
{% extends "base.html" %}
{% block title %}Categories List{% endblock %}
{% block page_heading %}Categories List{% endblock %}


{% block content %}
        
    <a href="{% url 'dashboard:add_book' %}" class="btn btn-primary float-right mb-3">Add Book</a>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Slug</th>
        <th>Icon</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        {% for category in categories %}

        <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.slug }}</td>
            <td>
                <img src="{{ category.icon.url }}" alt="{{ category.name }}" style="max-width: 50px; max-height: 50px;">
            </td>
            <td>
                <a href="{% url 'dashboard:delete_category' category.id %}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="4">No categories found.</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
 
{% endblock %}
{% block generate_report_button %}{% endblock %}

dashboard/templates/all_writers.html
{% extends "base.html" %}
{% block title %}Categories List{% endblock %}
{% block page_heading %}Categories List{% endblock %}


{% block content %}
        
    <a href="{% url 'dashboard:add_book' %}" class="btn btn-primary float-right mb-3">Add Book</a>
  <table class="table">
    <thead>
      <tr>
                <th>Name</th>
                <th>Slug</th>
                <th>Profile Picture</th>
                <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for writer in writers %}
            <tr>
                <td>{{ writer.name }}</td>
                <td>{{ writer.slug }}</td>
                <td>
                    <img src="{{ writer.profile_picture.url }}" alt="{{ writer.name }}" style="max-width: 50px; max-height: 50px;">
                </td>
                <td>
                    <a href="{% url 'dashboard:delete_writer' writer.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">No writers found.</td>
            </tr>
        {% endfor %}
    </tbody>

  </table>
 
{% endblock %}
{% block generate_report_button %}{% endblock %}

dashboard/templates/books_list.html
{% extends "base.html" %}
{% block title %}Books List{% endblock %}
{% block page_heading %}Books List{% endblock %}


{% block content %}
        
    <a href="{% url 'dashboard:add_book' %}" class="btn btn-primary float-right mb-3">Add Book</a>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Writer</th>
        <th>Category</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for book in books %}
        <tr>
          <td>{{ book.id }}</td>
          <td>{{ book.name }}</td>
          <td>{{ book.writer }}</td>
          <td>{{ book.category.name }}</td>
          <td>{{ book.price }}</td>
          <td>{{ book.stock }}</td>
          
          <td>
            <a href="{% url 'dashboard:edit_book' book.id %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'dashboard:delete_book' book.id %}" class="btn btn-danger">Delete</a>

        </td>
        
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No books available.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
 
{% endblock %}
{% block generate_report_button %}{% endblock %}

dashboard/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
							<div class="col-lg-6 d-none d-lg-block" style="background-image: url('{% static 'images/taaj.png' %}');  background-repeat: no-repeat; background-position: center; height: 600px"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4>Admin Login </h4>
										{% if messages %}
										<div class="messages">
											{% for message in messages %}
											<p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
											{% endfor %}
										</div>
										{% endif %}
                                    </div>
                                    <form action="" method="POST"  class="user auth-validate-form">
										{% csrf_token %}

                                        <div class="form-group">
											<input type="text" name="user" class="form-control form-control-user"
											placeholder="Username"> 
                                        </div> 

                                        <div class="form-group">
                                            <input type="password" name="pass" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>
                                        <hr>
                                        <a href="#" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>
                                        <a href="#" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                        </a>
                                    </form>
                                    <hr>
                                    
                                    <div class="text-center">
                                        <a class="small" href="{% url 'store:registration' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

dashboard/templates/orders.html
{% extends "base.html" %}
{% block title %}Orders{% endblock %}
{% block page_heading %}Orders{% endblock %}

{% block content %}
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Customer</th>
                                    <th>Transaction ID</th>
                                    <th>Address</th>
                                    <th>Payable Amount</th>
                                    <th>Total Books</th>
                                    <th>Payment Method</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                            </tr>
                        </thead>
                        <!-- <tfoot>
                            <tr>
                                <th>Customer</th>
                                <th>Transaction ID</th>
                                <th>Address</th>
                                <th>Payable Amount</th>
                                <th>Total Books (Quantity)</th>
                                <th>Payment Method</th>
                                <th>Payment Status</th>
                                <th>Actions</th>
                            </tr>

                        </tfoot> -->
                        <tbody>
                            <tr>
                                {% for order in orders %}

                                    <td>{{ order.name }}</td>
                                    <td>{{ order.transaction_id }}</td>
                                    <td>{{ order.address }}</td>
                                    <td>${{ order.payable }}</td>
                                    <td>{{ order.totalbook }}</td>
                                    <td>{{ order.payment_method }}</td>
                                    <td>
                                        <form method="post" action="{% url 'dashboard:change_payment_status' order.id %}">
                                            {% csrf_token %}
                                            <div class="form-group">
                                              <select class="form-control" name="payment_status" onchange="this.form.submit()">
                                                <option value="paid" {% if order.paid %}selected{% endif %}>Paid</option>
                                                <option value="unpaid" {% if not order.paid %}selected{% endif %}>Unpaid</option>
                                              </select>
                                            </div>
                                          </form>
                                    </td>
                                    <td>
                                    <a href="{% url 'dashboard:order_details' order.id %}" class="btn btn-info">Details</a>

                                    </td>
                                </tr>
                                {% empty %}
                                    <tr>
                                    <td colspan="8">No orders available.</td>
                                    </tr>
                                {% endfor %}
                            
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

                

{% endblock %}
{% block generate_report_button %}{% endblock %}